### ISSUE TITLE
1.5: JavaScript Functions Part 2

### ISSUE THREAD

**Issue by dkause** [dkause/PokeView-App#4]
**Part 1**
-[ ] replace for loop with for each

Use a forEach() function instead of the for loop you have to iterate over the Pokémon in your pokemonList array in order to print the details of each one. We recommend revisiting and carefully studying the userList example in this Exercise before doing this part of the task. Commit and push the changes to your GitHub repository.

**Part 2**
- [x] wrap pokemonList in IIFE
- [x] create pokemonRepository variable
- [x] assign IIFE to variable
- [ ] return object with two functions
    1. getAll: return all items of pokemomList
    2. add: add a single item  to pokemonList
- [x] update forEach() to local variabel assigned to pokemonlist
- [x]  commit and push to repository
- [x] submit link to cf
